# Generated by Django 3.2 on 2022-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hof',
            name='appearances',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hof',
            name='assists',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hof',
            name='goals',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hof',
            name='titles',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
