# Generated by Django 3.2 on 2022-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hof', '0002_auto_20220212_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='hof',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
